"""完全虚构、无真实身份的公开演示样例，不能充当人工金标准。"""

SAMPLES = [
    {"id": "graduate-python", "name": "应届生 · Python 数据方向", "scenario": "应届 / 有课程项目", "text": "本科应届，计算机相关专业。\n项目：使用Python和Pandas完成公开数据清洗与探索，使用SQL进行分组查询。\n使用Git管理代码，并为数据处理函数编写测试。熟悉Linux基础操作。\n了解机器学习，尚未使用TensorFlow。希望从Python开发或数据分析岗位起步。", "preferences": {"city": "深圳", "intent": "Python 数据分析", "education": "本科", "experience_years": 0, "salary_min": 8000, "district": ""}},
    {"id": "python-junior", "name": "开发者 · 2 年 Python 后端", "scenario": "1–3 年 / 后端开发", "text": "本科，2年工作经验，方向为Python后端开发。\n项目：使用Python和FastAPI开发数据接口，使用MySQL存储业务数据，使用Redis缓存查询结果。\n使用Docker部署服务，编写自动化测试，在Linux环境定位接口问题。\n熟悉Git协作与SQL查询优化，了解消息队列，尚未使用Kafka。", "preferences": {"city": "深圳", "intent": "Python 后端开发", "education": "本科", "experience_years": 2, "salary_min": 15000, "district": ""}},
    {"id": "transition-data", "name": "转岗者 · 运营转数据分析", "scenario": "转岗 / 可迁移能力", "text": "本科，2年工作经验，从运营转向数据分析。\n项目：使用Excel整理活动数据，使用SQL分析转化漏斗并撰写结论。\n使用Python和Pandas完成公开数据分析练习，使用Power BI制作报表。\n了解统计分析与A/B测试，暂无机器学习模型上线经验。", "preferences": {"city": "深圳", "intent": "数据分析师", "education": "本科", "experience_years": 2, "salary_min": 10000, "district": ""}},
    {"id": "frontend", "name": "前端工程师 · Vue 项目经历", "scenario": "替代技能组 / Vue 与 React", "text": "本科，2年开发经验，方向为前端工程师。\n项目：使用Vue和TypeScript开发管理平台，使用HTML和CSS完成响应式布局，使用JavaScript对接接口。\n使用Git进行团队协作，编写自动化测试。了解React，未掌握Java。", "preferences": {"city": "深圳", "intent": "前端开发", "education": "本科", "experience_years": 2, "salary_min": 12000, "district": ""}},
    {"id": "ml-senior", "name": "算法工程师 · PyTorch 经验", "scenario": "3–5 年 / 算法", "text": "硕士，4年工作经验，方向为机器学习算法。\n项目：使用Python和PyTorch训练文本分类模型，使用Transformer完成特征编码，并开展交叉验证与误差分析。\n使用Linux和Docker部署推理服务，使用SQL构建离线评估数据。\n熟悉机器学习、深度学习与自然语言处理；了解TensorFlow。", "preferences": {"city": "深圳", "intent": "机器学习 算法工程师", "education": "硕士", "experience_years": 4, "salary_min": 25000, "district": ""}},
    {"id": "incomplete", "name": "信息残缺 · 需要先追问", "scenario": "拒答校准", "text": "想找一份适合我的工作，希望能有成长。", "preferences": {"city": "", "intent": "", "education": "", "experience_years": None, "salary_min": None, "district": ""}},
    {"id": "keyword-list", "name": "对抗样例 · 只有技能关键词", "scenario": "避免将关键词当成实践能力", "text": "本科，1年工作经验。\n技能清单：Python、Java、SQL、Docker、PyTorch、TensorFlow、算法、深度学习、分布式。\n以上仅为收集的关键词，尚未说明相关项目。", "preferences": {"city": "深圳", "intent": "算法工程师", "education": "本科", "experience_years": 1, "salary_min": 15000, "district": ""}},
]
